name: "Deploy to nuget.org"
description: "Deploy to nuget.org"
    
runs:
  using: "composite"

  steps:
  - name: Download Artifacts
    uses: actions/download-artifact@v4
    with:
        name: NuGet-Signed
        path: artifacts

  - name: Uno NuGet Feed Push
    shell: pwsh
    run: |
        dotnet nuget push artifacts\*.nupkg -s https://pkgs.dev.azure.com/uno-platform/1dd81cbd-cb35-41de-a570-b0df3571a196/_packaging/unoplatformdev/nuget/v3/index.json -k "${{ secrets.UNO_NUGET_FEED_API_KEY }}"

